# Cloud Build config to run ONLY migrations
# Usage: gcloud builds submit --config=cloudbuild-migrate-only.yaml

steps:
  # Run database migrations
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Find the hero-api directory
        if [ -d "hero-api" ]; then
          cd hero-api
        fi
        npm install
        npx prisma generate
        npx prisma migrate deploy
    env:
      - 'DATABASE_URL=postgresql://dbuser:$$DB_PASSWORD@/docuhero?host=/cloudsql/docuhero-583a5:us-east1:docuhero-db&schema=public'
    secretEnv: ['DB_PASSWORD']

availableSecrets:
  secretManager:
    - versionName: projects/docuhero-583a5/secrets/db-password/versions/latest
      env: 'DB_PASSWORD'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

